# Generated by Django 3.2.9 on 2021-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='vehiclepassport',
            options={'verbose_name_plural': 'Паспорта машин'},
        ),
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepassport',
            name='engine_volume',
            field=models.SmallIntegerField(verbose_name='Объем двигателя, куб.см'),
        ),
        migrations.AlterModelTable(
            name='auto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vehiclepassport',
            table=None,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
