# Generated by Django 3.2.9 on 2022-02-01 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motorpool', '0014_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка')),
                ('text', models.TextField(default='', max_length=500, verbose_name='Текст отзыва')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='motorpool.auto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_rents', to='motorpool.auto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_rents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
